baseURL: "https://ilham-bintang.github.io"
title: Ilham Bintang
paginate: 8
theme: hugo-PaperMod
enableInlineShortcodes: true
enableRobotsTXT: true

googleAnalyticsID: "G-310104294"

minify:
  disableXML: true
  minifyOutput: true

languages:
  en:
    languageName: "English"
    weight: 1
    menu:
      main:
        - name: Archives
          url: /archives/
          weight: 5
        - name: Posts
          url: /posts/
          weight: 5
        - name: Tags
          url: /tags/
          weight: 10
    
    profileMode:
      enabled: true
      title: Ilham Bintang
      imageUrl: "abin.jpeg"
      imageTitle: Abin
      subtitle: "ğŸ§‘ğŸ»â€ğŸ’» Machine Learning Engineer | ğŸ‘¨ğŸ»â€ğŸ“ Master of Computer Science | ğŸŒ´ Lombok Island"
      buttons:
        - name: My Writing
          url: posts
        - name: Tags
          url: tags

    socialIcons:
      - name: linkedin
        url: "https://linkedin.com/in/nullphantom"
      - name: github
        url: "https://github.com/ilham-bintang"
      - name: twitter
        url: "https://twitter.com/ilham__py"
      - name: email
        url: "mailto:ilhambintang.ai@gmail.com"
